steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rummy-464118/wheel-fortune', '.']
    dir: 'wheel-fortune'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rummy-464118/wheel-fortune']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'wheel-fortune'
      - '--image'
      - 'gcr.io/rummy-464118/wheel-fortune'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/rummy-464118/wheel-fortune'
